### PR TITLE
Test task Hanna Kozak

### PR DESCRIPTION
**Pull request by hannakozak**
Style the listing component
Create and style cta component

### CODE REVIEW

**Comment by bbucek** [comment]
CTA:
- Not responsive

Cards:
- Hover effect not applied when hovering over text
- Cards should stretch and maintain similar spacing

Overall:
- Some good use of the predefined code from 'mono'

**Comment by hannakozak** [comment]
> CTA:
> 
> * Not responsive
> 
> Cards:
> 
> * Hover effect not applied when hovering over text
> * Cards should stretch and maintain similar spacing
> 
> Overall:
> 
> * Some good use of the predefined code from 'mono'

Thank you for the code review. 
I fixed responsiveness, but I am not sure about the second issue: ' Hover effect not applied when hovering over text'. According to Figma's description, I have previously applied the hover effect on the card element: 'The card has a subtle animated hover effect that can be previewed in the prototype. On hover the image zooms in slightly over 300ms.', but couldn't find any hover effect over text on the card in Figma design.

**Comment by rafzielinski** [comment]
Hi and thank you for your submission.
We like your implementation but we want to ask for few tweaks before we get to the final decision.

1. Button could use some subtle hover state
2. Alignment of CTA elements could be better on mobile.
3. Card image is distorted when changing the screen size, the `object-fit` rule should be applied to the image not the wrapper
4. Card zoom-in animation works only when you hover over the image, not when you're hovering over text on the bottom of the card.

**Comment by hannakozak** [comment]
Hi,
Thank you for the feedback. All suggestions are now implemented.

**Pull request closed without merging**
